channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==3.4.0
  - catboost==1.2.8
  - ipython==9.6.0
  - numpy==2.3.3
  - pandas==2.3.3
  - scipy==1.16.2
name: mlflow-env
